### ISSUE TITLE
Reaction Event Handlers Not Dispatching

### ISSUE THREAD

**Issue by zRyder** [serenity-rs/serenity#2923] opened 2024-07-26 19:51 UTC
When trying to implement adding/removing reactions. The handler implementations are not dispatched. Tested with `ReactionAdd` and `ReactionRemove`. When debugging, I had a non admin user add a reaction to a message, when I debugged, the bot with admin permissions did not run the code.

**Comment by jamesbt365** [comment] 2024-07-26 20:06
Show your intents.

**Comment by zRyder** [comment] 2024-07-26 20:10
Could you remind me what that is again?

**Comment by jamesbt365** [comment] 2024-07-26 20:12
They are the toggles that indicate to Discord what events to send you. You set these when you are creating the serenity client.

**Comment by zRyder** [comment] 2024-07-26 20:42
I see, I’ll provide them in a bit

**Comment by jamesbt365** [comment] 2024-08-23 09:19
This is either a duplicate of #2930 #2922, #2910, #2909, #2892 or user error.

**Closed as not planned by jamesbt365** 2024-08-23 09:19 UTC
