### ISSUE TITLE
`get_channel_archived_public_threads()` seems to not be using ISO8601 for the `before` parameter

### ISSUE THREAD

**Issue by Sirraide** [serenity-rs/serenity#2699] opened 2024-01-09 08:23 UTC
`get_channel_archived_public_threads()` (and possibly `get_channel_archived_private_threads()`; I’m not sure if that one is also affected) optionally takes a `before` parameter that is currently just an `Option<u64>` that gets converted to a string and then sent to the route, from what I can tell. However, the [Discord API docs](https://discord.com/developers/docs/resources/channel#list-public-archived-threads-query-string-params) specify that this parameter should be in the ISO8601 format.

As a result, when trying to pass e.g. a unix timestamp as a `u64` to `get_channel_archived_public_threads()`, I get the following error message after trying to execute this against a forum channel:
```
Invalid Form Body (before: Could not parse 1664162557. Should be ISO8601.)
```

**Comment by jamesbt365** [comment] 2024-01-09 14:57
This is a duplicate of #2664 and is fixed in #2665.

**Closed as completed** 2024-01-09 19:38 UTC
