### ISSUE TITLE
Support for oauth2 token exchanges?

### ISSUE THREAD

**Issue by ghost** [serenity-rs/serenity#2475] opened 2023-06-24 17:05 UTC
Would it be possible to add oauth2 token support? Having a library that supports the discord api, but having to manually make access token exchanges is tedious.

[Here's an example of what has to be sent](https://discord.com/developers/docs/topics/oauth2#authorization-code-grant-access-token-exchange-example)

[Here's an example response](https://discord.com/developers/docs/topics/oauth2#authorization-code-grant-access-token-response)

It would be much appreciated!

**Comment by valentinegb** [comment] 2024-08-03 19:36
I second this! It seems like I can't rely on Serenity for OAuth2 stuff at all since it doesn't even have the OAuth2 endpoints in [`Route`](https://docs.rs/serenity/latest/serenity/http/enum.Route.html)...

**Comment by GnomedDev** [comment] 2024-11-14 13:19
This looks like a duplicate of #762.

**Closed as not planned by GnomedDev** 2024-11-14 13:19 UTC
Labels: duplicate, feature-request
