### ISSUE TITLE
Context::quit() restarts instead of quitting

### ISSUE THREAD

**Issue by troiganto** [serenity-rs/serenity#284] opened 2018-03-02 23:13 UTC
For context, my use case boils down to that I'd like my discord bot to shut down whenever I ping it with a message that contains the string "!exit".

To do that, I call `Context::quit()` from within my `EventHandler`. (Function was added [here](https://github.com/zeyla/serenity/commit/561b0e38b4cda6661425f76c8d707d58d0f12d09).) Unfortunately, this doesn't work because the shard simply restarts after a second or so ([log](https://github.com/zeyla/serenity/files/1776771/restart.txt)). Judging by the documentation, I think this is not the intended behavior.

Minimal reproducing example:

```rust
extern crate env_logger;
#[macro_use]
extern crate log;
extern crate serenity;

use serenity::prelude::*;
use serenity::model::prelude::*;

pub struct Handler;

impl EventHandler for Handler {
    fn ready(&self, _: Context, _: Ready) {
        info!("ready!");
    }

    fn message(&self, context: Context, message: Message) {
        info!("{}: {}", message.author.name, message.content);
        if message.content.contains("!exit") {
            info!("Received exit command, exiting");
            context.quit();
        }
    }
}

fn main() {
    env_logger::init();
    let token = std::env::var("DISCORD_TOKEN").expect("DISCORD_TOKEN");
    let mut client = Client::new(&token, Handler).unwrap();
    client.start().unwrap();
}
```

Is there a better way to achieve what I want? I've tried `ShardManager::shutdown_all()`, but on its own, it doesn't "cleanly" shut down the bot; the member list shows it as online for another minute or so. My current workaround is rather hacky:

- call `Context::quit()` in the event handler and notify a "killswitch" thread,
- have the killswitch thread `join()` serenity's thread pool to ensure that the event handler has finished handling its message,
- lock the shard manager in the killswitch thread,
- sleep for a few milliseconds to ensure that the websocket has been closed,
- call `ShardManager::shutdown_all()` so that the shard doesn't restart.

No matter the resolution, thank you already for this wonderful crate! I'm coming from discord-rs and must say that serenity is much more pleasant to work with. :smiley:

**Comment by zeyla** [comment] 2018-03-02 23:20
The functionality of `Context::quit` is actually by design, the documentation is slightly inaccurate. Going through the `ShardManager` is the intended method.

The reason that the bot stays online in the member list for a while is because Discord will keep the session alive until it fails to receive a heartbeat from the bot for some time. Cleanly closing the websocket should probably be the preferred functionality.

**Comment by troiganto** [comment] 2018-03-02 23:35
That makes sense. I've tried to familiarize myself with the code a bit. It seems that both `Context::quit` and `ShardManager::shutdown` eventually wind up making the `ShardRunner` execute these three lines:

```rust
let close_data = CloseData::new(1000, String::new());
let msg = OwnedMessage::Close(Some(close_data));
let _ = self.shard.client.send_message(&msg);
```

where `self.shard.client` is a websocket. I've got no experience with websockets, so I have to guess here — but could there be a timing issue here? Would `shutdown_all` have to wait in some manner for the websocket to send out the closing message?

**Comment by shelvacu** [comment] 2019-05-31 12:38
In addition to documentation, I would suggest changing the method name, something like "websocket_close" or even "shard_websocket_close".

I would assume that #70 was originally meant to ask for a method to gracefully shutdown websocket connections, join threads, etc. and then return from Client::start (which in most programs would then exit)

**Closed** 2019-06-09 10:17 UTC
Labels: docs, enhancement
