### ISSUE TITLE
VoiceState.channel_id None when it shouldn't be

### ISSUE THREAD

**Issue by sasjafor** [serenity-rs/serenity#513] opened 2019-03-16 14:14 UTC
I have written a simple bot which reacts to voice state updates.

Now when I switch from a normal voice channel to a voice channel with "Connect" permission restricted on discord, the field VoiceState.channel_id is None. But when I already am in that channel,  the channel_id is Some and the bot can join the channel.
The bot has the necessary "Connect" permission, and it can join when I have a channel_id to pass.

Serenity version: rev = "722e1cc" on branch v0.6.x (because of issue with openssl 1.1.1)

Rust version (`rustc -V`): `rustc 1.33.0 (2aa4c46cf 2019-02-28)`

Minimal test case if possible: 
- Discord Server with two voice channels
  - One normal
  - One with "connect" permission restrict for @everyone
- Give "connect" permission to bot
- Join normal channel
- Switch to restricted channel
- Check `voice_state.channel_id` from `fn voice_state_update`

EDIT: On a different server with the exact same settings, it seems to work without problems. However, I have written a very similar bot in JS using discord-js and that one can retrieve the channel id and join when doing the exact same test (where the bot using serenity fails), with the same settings on discord.

**Comment by sasjafor** [comment] 2019-03-17 11:28
I can confirm that it doesn't happen on `version = "0.5.13"`. Luckily the docker rust:1.33 image can build serenity without openssl issues.

**Comment by Erk-** [comment] 2019-03-17 16:00
Until it is fixed you can also use this trick to fix the issue https://github.com/serenity-rs/serenity/issues/394#issuecomment-425785602 

(Just to let you know if you run the binary build in docker on a machine with another openssl version it may segfault)

**Comment by Lakelezz** [comment] 2019-05-03 18:24
I tried and could not reproduce this (on 5fa5dbf66b45d6db4739e8bcc25697ccfcf09767), neither on the new nor old `VoiceState`. While the *old* being the one grabbed from the cache prior updating it.

**Comment by Lakelezz** [comment] 2019-05-06 13:37
I added `help_wanted` as I would like other people to try to reproduce this because I could not.

**Comment by ghost** [comment] 2019-06-09 07:25
Can't reproduce using 7c61f958b139159a6c4595f6c99d7812d69d339b, closing for now. If you can reproduce it with debugging information and a sample program please let us know and it can be re-opened.

**Closed by ghost** 2019-06-09 07:25 UTC
Labels: help wanted, possible bug, voice
