### ISSUE TITLE
Grabbing a message off of a reaction causes burst_colour field missing

### ISSUE THREAD

**Issue by Alacho2** [serenity-rs/serenity#2930] opened 2024-08-02 17:16 UTC
For the record, I might be holding it wrong.

I have a bot that reacts to a Reaction coming in, checking for whether the user reacting is part of a role and then grabbing the author of the message off of the reaction.

This used to be done something like:
```
  let message = channel_id.message(&ctx.http, message_id).await?;
  let author = message.author.id;
```

Where the channel_id and message_id come from the reaction struct, respectfully.
However, when done this way, Serenity spits out: Error: Serenity error: missing field `burst_colours` at line 1 column 773.

These are my intents:
```
  let intents = GatewayIntents::default()
    | GatewayIntents::MESSAGE_CONTENT
    | GatewayIntents::GUILD_MEMBERS
    | GatewayIntents::GUILDS;
```

I also noticed that when I perform the same operation from an incoming message (not a reaction), it works fine.
I also know that I can use the message_author_id property.

**Comment by jamesbt365** [comment] 2024-08-02 17:25
Duplicate of #2922, #2910, #2909, #2892. Please check existing issues before opening one in the future.

**Closed as not planned by jamesbt365** 2024-08-02 17:25 UTC
Labels: duplicate
