### ISSUE TITLE
guild_update uses new name in old_data

### ISSUE THREAD

**Issue by ghost** [serenity-rs/serenity#805] opened 2020-03-18 14:07 UTC
On the docs, it says:
> Provides the guild's old full data (if available) and the new, albeit partial data.

# Actions
```toml
[dependencies.serenity]
version = "0.8"
default_features = true
```
```Rust
pub struct Handler;

impl EventHandler for Handler {
  fn guild_update(
    &self,
    ctx: Context,
    old_guild: Option<Arc<RwLock<Guild>>>,
    new_guild: PartialGuild,
  ) {
    if let Some(old_guild) = old_guild {
      let data = old_guild.read();
      if new_guild.name == data.name {
        println!("Guild Updated: {} to {}", data.name, new_guild.name);
        return;
      }

      println!("Guild Renamed: {} to {}", data.name, new_guild.name);
    }
  }
}
```

I renamed my Discord server from Old_Name to New_Name.

# Expected
If `old_guild` isn't available, I don't expect it to print anything.
If `old_guild` is available, I expect it to print out: "Guild Renamed: OId_Name to New_Name"

# Actual
It prints: "Guild Updated: New_Name to New_Name"

**Comment by rasm47** [comment] 2021-07-01 13:06
I propose closing this issue. The `guild_update` signature seems to have changed.

`Cargo.toml`
```
[dependencies]
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
serenity = { version = "0.10", default-features = false, features = ["client", "gateway", "rustls_backend", "model"] }
```

`main.rs`
```rust
use serenity::{async_trait, model::prelude::*, prelude::*};

struct Handler;

#[async_trait]
impl EventHandler for Handler {
    async fn guild_update(&self, _ctx: Context, new_data: PartialGuild) {
        println! {"new_data.name:\n{:#?}", new_data.name};
    }
}

#[tokio::main]
async fn main() {
    let token = "REDACTED";

    let mut client = Client::builder(&token)
        .event_handler(Handler)
        .await
        .expect("Err creating client");

    if let Err(why) = client.start().await {
        println!("Client error: {:?}", why);
    }
}
```

There is no `old_guild` in 0.10.8. In my tests, `new_data.name` contains the new name of the updated Discord channel.

**Comment by arqunis** [comment] 2021-07-01 13:33
> There is no old_guild in `0.10.8`.

There is, it is just gated [behind the `cache` feature](https://serenity-rs.github.io/serenity/current/src/serenity/client/event_handler.rs.html#249-255).

**Comment by rasm47** [comment] 2021-07-01 19:09
I made a better (but still unsuccessful) attampt at replicating the issue, this time with `cache`.

`Cargo.toml`
```
[dependencies]
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
serenity = { version = "0.10", default-features = false, features = ["client", "gateway", "rustls_backend", "model", "cache"] }
```

`main.rs`
```rust
    async fn guild_update(&self, _ctx: Context, old_data: Option<Guild>, new_data: PartialGuild) {
        if let Some(od) = old_data {
            println! {"old_data.name: {:#?}", od.name};
        } else {
            println! {"old_data was None"};
        }
        println! {"new_data.name: {:#?}", new_data.name};
    }
```



When I changed the name of my Discord server from changeme to changed, the console printed:
```
old_data.name: "changeme"
new_data.name: "changed"
```

**Comment by kangalio** [comment] 2022-09-17 10:42
I cannot reproduce either
![Screenshot_20220917_123803](https://user-images.githubusercontent.com/21220820/190852613-aa007314-e5e6-45d4-b816-cc9c73a1d380.png)

According to the code, the old guild data is retrieved before the update event is incorporated into the cache, which also seems correct

https://github.com/serenity-rs/serenity/blob/2eea7d792615c25ed904d08ec5931d935a314e9a/src/client/dispatch.rs#L604-L609

I propose we close this issue. It can be reopened if someone manages to reproduce after all

**Closed as completed** 2022-09-17 10:49 UTC
Labels: bug
