### ISSUE TITLE
Follow the Rust API Guidelines

### ISSUE THREAD

**Issue by zeyla** [serenity-rs/serenity#171] opened 2017-10-02 18:40 UTC
We should ensure we follow all of the checkboxes on this list: <https://rust-lang-nursery.github.io/api-guidelines/checklist.html>

PRs for only one or a couple checkboxes are perfectly fine.

List here:

- **Organization** *(crate is structured in an intelligible way)*
  - [x] Crate root re-exports common functionality ([C-REEXPORT])
  - [x] Modules provide a sensible API hierarchy ([C-HIERARCHY])
- **Naming** *(crate aligns with Rust naming conventions)*
  - [ ] Casing conforms to RFC 430 ([C-CASE])
  - [ ] Ad-hoc conversions follow `as_`, `to_`, `into_` conventions ([C-CONV])
  - [x] Methods on collections that produce iterators follow `iter`, `iter_mut`, `into_iter` ([C-ITER])
  - [x] Iterator type names match the methods that produce them ([C-ITER-TY])
  - [ ] Ownership suffixes use `_mut` and `_ref` ([C-OWN-SUFFIX])
  - [ ] Single-element containers implement appropriate getters ([C-GETTERS])
  - [x] Feature names are free of placeholder words ([C-FEATURE])
- **Interoperability** *(crate interacts nicely with other library functionality)*
  - [ ] Types eagerly implement common traits ([C-COMMON-TRAITS])
    - `Copy`, `Clone`, `Eq`, `PartialEq`, `Ord`, `PartialOrd`, `Hash`, `Debug`,
      `Display`, `Default`
  - [ ] Conversions use the standard traits `From`, `AsRef`, `AsMut` ([C-CONV-TRAITS])
  - [x] Collections implement `FromIterator` and `Extend` ([C-COLLECT])
  - [ ] Data structures implement Serde's `Serialize`, `Deserialize` ([C-SERDE])
  - [ ] Types are `Send` and `Sync` where possible ([C-SEND-SYNC])
  - [ ] Error types are `Send` and `Sync` ([C-SEND-SYNC-ERR])
  - [ ] Error types are meaningful, not `()` ([C-MEANINGFUL-ERR])
  - [x] Binary number types provide `Hex`, `Octal`, `Binary` formatting ([C-NUM-FMT])
- **Macros** *(crate presents well-behaved macros)*
  - [x] Input syntax is evocative of the output ([C-EVOCATIVE])
  - [x] Macros compose well with attributes ([C-MACRO-ATTR])
  - [x] Item macros work anywhere that items are allowed ([C-ANYWHERE])
  - [x] Item macros support visibility specifiers ([C-MACRO-VIS])
  - [x] Type fragments are flexible ([C-MACRO-TY])
- **Documentation** *(crate is abundantly documented)*
  - [ ] Crate level docs are thorough and include examples ([C-CRATE-DOC])
  - [ ] All items have a rustdoc example ([C-EXAMPLE])
  - [ ] Examples use `?`, not `try!`, not `unwrap` ([C-QUESTION-MARK])
  - [ ] Function docs include error conditions in "Errors" section ([C-ERROR-DOC])
  - [x] Function docs include panic conditions in "Panics" section ([C-PANIC-DOC])
  - [x] Prose contains hyperlinks to relevant things ([C-LINK])
  - [x] Cargo.toml includes all common metadata ([C-METADATA])
    - authors, description, license, homepage, documentation, repository,
      readme, keywords, categories
  - [x] Cargo.toml documentation key points to "https://docs.rs/CRATE" ([C-DOCS-RS])
  - [x] Crate sets html_root_url attribute "https://docs.rs/CRATE/VER.SI.ON" ([C-HTML-ROOT])
  - [x] Release notes document all significant changes ([C-RELNOTES])
- **Predictability** *(crate enables legible code that acts how it looks)*
  - [x] Smart pointers do not add inherent methods ([C-SMART-PTR])
  - [ ] Conversions live on the most specific type involved ([C-CONV-SPECIFIC])
  - [x] Functions with a clear receiver are methods ([C-METHOD])
  - [x] Functions do not take out-parameters ([C-NO-OUT])
  - [x] Operator overloads are unsurprising ([C-OVERLOAD])
  - [x] Only smart pointers implement `Deref` and `DerefMut` ([C-DEREF])
  - [x] `Deref` and `DerefMut` never fail ([C-DEREF-FAIL])
  - [x] Constructors are static, inherent methods ([C-CTOR])
- **Flexibility** *(crate supports diverse real-world use cases)*
  - [x] Functions expose intermediate results to avoid duplicate work ([C-INTERMEDIATE])
  - [x] Caller decides where to copy and place data ([C-CALLER-CONTROL])
  - [ ] Functions minimize assumptions about parameters by using generics ([C-GENERIC])
  - [x] Traits are object-safe if they may be useful as a trait object ([C-OBJECT])
- **Type safety** *(crate leverages the type system effectively)*
  - [x] Newtypes provide static distinctions ([C-NEWTYPE])
  - [x] Arguments convey meaning through types, not `bool` or `Option` ([C-CUSTOM-TYPE])
  - [x] Types for a set of flags are `bitflags`, not enums ([C-BITFLAG])
  - [x] Builders enable construction of complex values ([C-BUILDER])
- **Dependability** *(crate is unlikely to do the wrong thing)*
  - [ ] Functions validate their arguments ([C-VALIDATE])
  - [x] Destructors never fail ([C-DTOR-FAIL])
  - [x] Destructors that may block have alternatives ([C-DTOR-BLOCK])
- **Debuggability** *(crate is conducive to easy debugging)*
  - [x] All public types implement `Debug` ([C-DEBUG]) (completed: #173)
  - [x] `Debug` representation is never empty ([C-DEBUG-NONEMPTY])
- **Future proofing** *(crate is free to improve without breaking users' code)*
  - [ ] Structs have private fields ([C-STRUCT-PRIVATE])
  - [x] Newtypes encapsulate implementation details ([C-NEWTYPE-HIDE])
  - [x] Data structures do not duplicate derived trait bounds ([C-STRUCT-BOUNDS])
- **Necessities** *(to whom they matter, they really matter)*
  - [x] Public dependencies of a stable crate are stable ([C-STABLE])
  - [x] Crate and its dependencies have a permissive license ([C-PERMISSIVE])

[C-REEXPORT]: https://rust-lang-nursery.github.io/api-guidelines/organization.html#c-reexport
[C-HIERARCHY]: https://rust-lang-nursery.github.io/api-guidelines/organization.html#c-hierarchy

[C-CASE]: https://rust-lang-nursery.github.io/api-guidelines/naming.html#c-case
[C-CONV]: https://rust-lang-nursery.github.io/api-guidelines/naming.html#c-naming
[C-ITER]: https://rust-lang-nursery.github.io/api-guidelines/naming.html#c-iter
[C-ITER-TY]: https://rust-lang-nursery.github.io/api-guidelines/naming.html#c-iter-ty
[C-OWN-SUFFIX]: https://rust-lang-nursery.github.io/api-guidelines/naming.html#c-own-suffix
[C-GETTERS]: https://rust-lang-nursery.github.io/api-guidelines/naming.html#c-getters
[C-FEATURE]: https://rust-lang-nursery.github.io/api-guidelines/naming.html#c-feature

[C-COMMON-TRAITS]: https://rust-lang-nursery.github.io/api-guidelines/interoperability.html#c-common-traits
[C-CONV-TRAITS]: https://rust-lang-nursery.github.io/api-guidelines/interoperability.html#c-conv-traits
[C-COLLECT]: https://rust-lang-nursery.github.io/api-guidelines/interoperability.html#c-collect
[C-SERDE]: https://rust-lang-nursery.github.io/api-guidelines/interoperability.html#c-serde
[C-SERDE-CFG]: https://rust-lang-nursery.github.io/api-guidelines/interoperability.html#c-serde-cfg
[C-SEND-SYNC]: https://rust-lang-nursery.github.io/api-guidelines/interoperability.html#c-send-sync
[C-SEND-SYNC-ERR]: https://rust-lang-nursery.github.io/api-guidelines/interoperability.html#c-send-sync-err
[C-MEANINGFUL-ERR]: https://rust-lang-nursery.github.io/api-guidelines/interoperability.html#c-meaningful-err
[C-NUM-FMT]: https://rust-lang-nursery.github.io/api-guidelines/interoperability.html#c-num-fmt

[C-EVOCATIVE]: https://rust-lang-nursery.github.io/api-guidelines/macros.html#c-evocative
[C-MACRO-ATTR]: https://rust-lang-nursery.github.io/api-guidelines/macros.html#c-macro-attr
[C-ANYWHERE]: https://rust-lang-nursery.github.io/api-guidelines/macros.html#c-anywhere
[C-MACRO-VIS]: https://rust-lang-nursery.github.io/api-guidelines/macros.html#c-macro-vis
[C-MACRO-TY]: https://rust-lang-nursery.github.io/api-guidelines/macros.html#c-macro-ty

[C-CRATE-DOC]: https://rust-lang-nursery.github.io/api-guidelines/documentation.html#c-crate-doc
[C-EXAMPLE]: https://rust-lang-nursery.github.io/api-guidelines/documentation.html#c-example
[C-QUESTION-MARK]: https://rust-lang-nursery.github.io/api-guidelines/documentation.html#c-question-mark
[C-ERROR-DOC]: https://rust-lang-nursery.github.io/api-guidelines/documentation.html#c-error-doc
[C-PANIC-DOC]: https://rust-lang-nursery.github.io/api-guidelines/documentation.html#c-panic-doc
[C-LINK]: https://rust-lang-nursery.github.io/api-guidelines/documentation.html#c-link
[C-METADATA]: https://rust-lang-nursery.github.io/api-guidelines/documentation.html#c-metadata
[C-DOCS-RS]: https://rust-lang-nursery.github.io/api-guidelines/documentation.html#c-docs-rs
[C-HTML-ROOT]: https://rust-lang-nursery.github.io/api-guidelines/documentation.html#c-html-root
[C-RELNOTES]: https://rust-lang-nursery.github.io/api-guidelines/documentation.html#c-relnotes

[C-SMART-PTR]: https://rust-lang-nursery.github.io/api-guidelines/predictability.html#c-smart-ptr
[C-CONV-SPECIFIC]: https://rust-lang-nursery.github.io/api-guidelines/predictability.html#c-conv-specific
[C-METHOD]: https://rust-lang-nursery.github.io/api-guidelines/predictability.html#c-method
[C-NO-OUT]: https://rust-lang-nursery.github.io/api-guidelines/predictability.html#c-no-out
[C-OVERLOAD]: https://rust-lang-nursery.github.io/api-guidelines/predictability.html#c-overload
[C-DEREF]: https://rust-lang-nursery.github.io/api-guidelines/predictability.html#c-deref
[C-DEREF-FAIL]: https://rust-lang-nursery.github.io/api-guidelines/predictability.html#c-deref-fail
[C-CTOR]: https://rust-lang-nursery.github.io/api-guidelines/predictability.html#c-ctor

[C-INTERMEDIATE]: https://rust-lang-nursery.github.io/api-guidelines/flexibility.html#c-intermediate
[C-CALLER-CONTROL]: https://rust-lang-nursery.github.io/api-guidelines/flexibility.html#c-caller-control
[C-GENERIC]: https://rust-lang-nursery.github.io/api-guidelines/flexibility.html#c-generic
[C-OBJECT]: https://rust-lang-nursery.github.io/api-guidelines/flexibility.html#c-object

[C-NEWTYPE]: https://rust-lang-nursery.github.io/api-guidelines/type-safety.html#c-newtype
[C-CUSTOM-TYPE]: https://rust-lang-nursery.github.io/api-guidelines/type-safety.html#c-custom-type
[C-BITFLAG]: https://rust-lang-nursery.github.io/api-guidelines/type-safety.html#c-bitflag
[C-BUILDER]: https://rust-lang-nursery.github.io/api-guidelines/type-safety.html#c-builder

[C-VALIDATE]: https://rust-lang-nursery.github.io/api-guidelines/dependability.html#c-validate
[C-DTOR-FAIL]: https://rust-lang-nursery.github.io/api-guidelines/dependability.html#c-dtor-fail
[C-DTOR-BLOCK]: https://rust-lang-nursery.github.io/api-guidelines/dependability.html#c-dtor-block

[C-DEBUG]: https://rust-lang-nursery.github.io/api-guidelines/debuggability.html#c-debug
[C-DEBUG-NONEMPTY]: https://rust-lang-nursery.github.io/api-guidelines/debuggability.html#c-debug-nonempty

[C-STRUCT-PRIVATE]: https://rust-lang-nursery.github.io/api-guidelines/future-proofing.html#c-struct-private
[C-NEWTYPE-HIDE]: https://rust-lang-nursery.github.io/api-guidelines/future-proofing.html#c-newtype-hide
[C-STRUCT-BOUNDS]: https://rust-lang-nursery.github.io/api-guidelines/future-proofing.html#c-struct-bounds

[C-STABLE]: https://rust-lang-nursery.github.io/api-guidelines/necessities.html#c-stable
[C-PERMISSIVE]: https://rust-lang-nursery.github.io/api-guidelines/necessities.html#c-permissive

**Comment by jhelwig** [comment] 2017-10-02 22:37
Might be worth reproducing the list here, so it can be updated as people tick things off, and to make it easier for people to see which things they should take a look at doing?

**Comment by zeyla** [comment] 2017-10-02 23:30
Sure, I'll get to that in a few hours and see what's already done and post here when it's made.

**Comment by zeyla** [comment] 2017-10-03 03:38
I've updated the OP, I believe it's accurate over a quick scan of the codebase.

**Comment by Coding-Doctors** [comment] 2017-11-08 14:19
Debugability is done as of the closing of 173

**Comment by zeyla** [comment] 2017-11-08 18:10
Updated, thanks

**Comment by FliegendeWurst** [comment] 2018-03-11 13:21
Errors were ```Sync``` in 0.4, but aren't in 0.5. The commit that broke it: [be43836](https://github.com/zeyla/serenity/commit/be43836839a31714f58e3ffe81dd4b0aeab2ab59) (the hyper Response does not implement Sync)

**Comment by Arzte** [comment] 2018-03-11 17:18
``C-SERDE-CFG`` is no longer in the rust API Guidelines

**Comment by ghost** [comment] 2019-06-10 16:24
Closed because this is a large issue that can't really be solved like a checklist (this issue is out of date, probably a lot). Closing for now, and it can be improved over time as issues are found and refactoring is done.

**Closed by ghost** 2019-06-10 16:24 UTC
Labels: enhancement, help wanted
