### ISSUE TITLE
CreateEmbed should implement serde's `Serialize` and `Deserialize`. 

### ISSUE THREAD

**Issue by loganintech** [serenity-rs/serenity#2338] opened 2023-02-02 07:24 UTC
Or at the very least, should have a function `to_embed(self) -> Embed` because `Embed` does implement `Serialize/Deserialize`

Edit: just noticed: https://github.com/serenity-rs/serenity/pull/2337

**Comment by kangalio** [comment] 2023-04-07 16:25
Duplicate of #2337

**Closed as not planned by kangalio** 2023-04-07 16:25 UTC
