### ISSUE TITLE
Json error while reading message history when reactions appear

### ISSUE THREAD

**Issue by emilyinure** [serenity-rs/serenity#2972] opened 2024-09-16 23:56 UTC
getting a json error value any time the message iterator comes across a reaction
```
Error("missing` field `burst_colours`", line: 1, column: 22489)
```

my code:
```
    while let Some(message_result) = messages.next().await {
        match message_result { // getting error val here
            Ok(message) => {
```

**Comment by GnomedDev** [comment] 2024-09-17 00:00
Duplicate of #2892.

**Closed as not planned by GnomedDev** 2024-09-17 00:00 UTC
Labels: duplicate
